### ISSUE TITLE
Missing ressources!

### ISSUE THREAD

**Issue by Kjarrigan** [D3nX/space_race#1]
Hi @D3nX ,

just pulled your latest changes and you forgot to add some files. As far as I can tell at least all ship-samples are missing:
* shot.wav
* explosion.wav
* collide.wav
* booster_sound.wav

and some images as well:

- bullet.png
- booster_normal.png
- booster_super.png
- booster_hyper.png
- the whole asteroids/ folder

Couldn't really test it but as you introduced more controls and stuff you might think about an "help"-screen explaining in brief how to play (like Arrows to move, Space to shoot, What does boosters do, etc)

And if you're already creating a new screen you could add an about/credits thingy where you can show Gosu::LICENSES

> A block of legal copy that your game is obliged to display somewhere.
> - http://www.rubydoc.info/github/gosu/gosu/Gosu

But otherwise seems like you introduced quite some stuff :+1:

**Comment by D3nX** [comment]
Hey, thank you for reporting it, l'ill fix it really soon ! I think I will first add missing files in a few moment and then add the help screen with legal information.
Thanks again =)

**Comment by D3nX** [comment]
Hey, the missing file should be uploaded right now ! ^^

**Comment by Kjarrigan** [comment]
It works and looks quite nice! Good job. I'll test it a bit more an might report back if I find any bugs or weird behavior :+1:  

UPDATE - I got a new Highscore 57.241 m + 11662 points :tada: . I like the new shooting mechanic. Before the giant swarms of aliens were sometime undodgeable - now I can shoot them. Although there are sometimes situations with lots of aliens and asteroids but thats ok - there has to be some sort of challenge.

**Comment by D3nX** [comment]
Haha ! Amazing score ! I'm happy you take fun playing at my game, really make me **happy** !
